# Generated by Django 4.2.1 on 2023-08-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=100)),
                ('aadhar_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
