# Generated by Django 4.2.1 on 2023-08-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Your Default Address', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default='2000-10-22'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Your Default Address', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='Your Default Address', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default='Your Default Address', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='pan_no',
            field=models.CharField(default='Your Default Address', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='Your Default Address', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='Your Default Address', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Your Default Address', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip',
            field=models.CharField(default='Your Default Address', max_length=100),
        ),
    ]
