# Generated by Django 4.1.10 on 2023-08-27 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_attendance_meetingevent_profile_delete_userprofile'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='attendance',
            name='account_no',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_app.profile'),
        ),
    ]
