# Generated by Django 4.1.10 on 2023-08-27 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_meetingevent_profile_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingEvent',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('meeting_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_place', models.CharField(default='Your usual meeting Address', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('aadhar_no', models.CharField(max_length=100)),
                ('pan_no', models.CharField(default='Your Default Address', max_length=100)),
                ('email', models.EmailField(default='Your Default Address', max_length=100)),
                ('mobile', models.CharField(default='Your Default Address', max_length=100)),
                ('username', models.CharField(default='Your Default Address', max_length=100)),
                ('password', models.CharField(default='Your Default Address', max_length=100)),
                ('birthday', models.DateField()),
                ('address', models.CharField(default='Your Default Address', max_length=100)),
                ('city', models.CharField(default='Your Default Address', max_length=100)),
                ('state', models.CharField(default='Your Default Address', max_length=100)),
                ('zip', models.CharField(default='Your Default Address', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Userprofile',
        ),
        migrations.AlterField(
            model_name='Attendance',
            name='account_no',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin_app.profile'),
        ),
    ]
