# Generated by Django 4.1.10 on 2023-08-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_meetingevent_profile_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Attendance',
            name='account_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.profile'),
        ),
    ]
